yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.IMommyHere.as_view(), name='author'),
    path('tech/', views.Tech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
LIMIT_POST: int = 15
LIMIT_COMMENT: int = 250


class Group(models.Model):
    title = models.CharField(
        verbose_name='Заголовок группы',
        max_length=200,
        help_text='Придумайте название группы')
    slug = models.SlugField(
        verbose_name='Адрес для страницы группы',
        max_length=100,
        unique=True)
    description = models.TextField(
        verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Расскажите о чём-то интересном')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    db_index=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста')
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Выберите группу')
    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Размер картинки 960 на 339, картинки обрезаются',
        upload_to='posts/',
        blank=True)

    def __str__(self):
        return self.text[: LIMIT_POST]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария')
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')

    def __str__(self):
        return self.text[: LIMIT_COMMENT]

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique subs'
            )
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels_text = {
            'text': ('текст'),
        }
        labels_group = {
            'group': ('группа'),
        }
        labels_image = {
            'image': ('картинка'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': ('текст'),
        }

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render
from .utils import paginator_for_page
from .models import Group, Post, Follow
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.shortcuts import redirect


User = get_user_model()
LIMIT: int = 10


def index(request):
    post_list = Post.objects.all()
    context = {
        'page_obj': paginator_for_page(post_list, request, LIMIT), }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).all()
    context = {
        'group': group,
        'page_obj': paginator_for_page(posts, request, LIMIT),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.all()
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'page_obj': paginator_for_page(user_posts, request, LIMIT),
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post_id,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': paginator_for_page(posts, request, LIMIT),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author
    )
    follow.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {%else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
          {% load user_filters %}
          {% if is_edit %}
          <form method="post" action="{% url 'posts:post_edit' post_id %}" enctype="multipart/form-data">
          {% else %}
          <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
          {% endif %}
          {% csrf_token %}
            <div>
            {% for field in form %}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text }}
                </small>
              {% endif %}
            {{ field|addclass:'form-control' }}
            {% endfor %}
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                  Сохранить
              </button>
              {% if post.group %}
              <a href="{% url 'posts:profile' post.group.slug %}">все записи группы</a>
              {% endif %}
             </div>
         </form>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Избранные авторы
{% endblock %}

{% block priview %}
  <h1>Избранные авторы</h1>
  <h3>Здесь представлены обновления ваших подписок</h3>
{% endblock %}

{% block content %}

  {% include 'posts/includes/switcher.html' %}

  {% for post in page_obj %}
  <ul>
    <li>
      Автор:
      <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}

  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>

  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}

  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

{% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи группы
{% endblock %}

{% block priview %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
{% endblock %}

{% block content %}
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <p>{{ post.text }}</p>
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% load cache %}
{% cache 20 index_page %}

{% block priview %}
  <h1>Последние обновления на сайте</h1>
  <h3>Здесь представлены все обновления</h3>
{% endblock %}

{% block content %}

  {% include 'posts/includes/switcher.html' %}

  {% for post in page_obj %}
  <ul>
    <li>
      Автор:
      <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}

  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>

  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}"><br>все записи группы: <b>{{ post.group.title }}</b></br></a>
  {% endif %}

  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

{% include 'posts/includes/paginator.html' %}

{% endblock %}

{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  Пост: {{ post.text }}
{% endblock %}

{% block priview %}
  <h1>Пост пользователя: {{ post.author.get_full_name }}</h1>
  <h3>Подробная информация о посте</h3>
{% endblock %}

{% block content %}
<ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      Группа: {{ post.group }}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </li>
  </ul>
  {% if not forloop.last %}<hr>{% endif %}
  <p>{{ post.text }}</p>
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  {% if not forloop.last %}<hr>{% endif %}
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {% for field in form %}
          {{ field|addclass:'form-control' }}
          {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

{% if not forloop.last %}<hr>{% endif %}
  {% if user == post.author %}
    <a href="{% url 'posts:post_edit' post.pk %}">
      <h5>Редактировать запись</h5>
    </a>
  {% endif %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block priview %}
  <h1>Все посты пользователя: {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
{% endblock %}

{% block content %}
<div class="mb-5">
{% if request.user ==  author %}
 
{% else %}
  {% if following %}
  <a
    class="btn btn-lg btn-light"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
  >
    Отписаться
  </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
{% endif %}
</div>

{% if not forloop.last %}<hr>{% endif %}
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>

  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}

  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 

  {% include 'posts/includes/paginator.html' %}  
{% endblock %}